apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: academy
  region: eu-west-1
  version: "1.19"

managedNodeGroups:
  - name: t3-small
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    instanceType: t3.small
    volumeSize: 50
    ssh:
      allow: true
      publicKeyName: new_id_rsa
    labels:
      role: worker
