name: Account Docker image

on:
  push:
    branches:
      - main
    paths:
      - "api/account/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          cd api/account/
          docker build . -t sonufrienko/academy-account:$(date +%s)
      - name: Push
        run: |
          docker push sonufrienko/academy-account:$(date +%s)
