name: Courses Docker image

on:
  push:
    branches:
      - main
    paths:
      - "api/courses/**"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        run: |
          cd api/courses/
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/academy-courses:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/academy-courses:latest
